### ISSUE TITLE
Problems compiling with ubuntu 18.04

### ISSUE THREAD

**Issue by h-bog** [daichengkai/VoxelMultiAxisAM#2]
Hi and thank you for sharing your code.

When trying to build following the steps described in the readme-file, I encounter a problem. I am currently trying to compile on Ubuntu 18.04. The build files are written successfully to the build-folder, but when trying to "make" errors occur after "Scanning dependencies of target VoxelMultiAxisAM_bin". At 79%: "Building CXX object CMakeFiles/VoxelMultiAxisAM_bin.dir/src/main.cpp.o" I get the following errors:

```
VoxelMultiAxisAM/src/main.cpp: In function ‘bool pre_draw(igl::opengl::glfw::Viewer&)’: 
/VoxelMultiAxisAM/src/main.cpp:50:12: error: invalid use of member function ‘const igl::opengl::ViewerCore& igl::opengl::glfw::Viewer::core(unsigned int) const’ (did you forget the ‘()’ ?)
       viewer.core.align_camera_center(V_Platform, F_Platform);

VoxelMultiAxisAM/src/main.cpp: In function ‘int main(int, char**)’:
VoxelMultiAxisAM/src/main.cpp:349:12: error: invalid use of member function ‘const igl::opengl::ViewerCore& igl::opengl::glfw::Viewer::core(unsigned int) const’ (did you forget the ‘()’ ?)
      viewer.core.background_color = Eigen::Vector4f(50. / 255., 50. / 255., 50. / 255., 1.0);

^CCMakeFiles/VoxelMultiAxisAM_bin.dir/build.make:62: recipe for target 'CMakeFiles/VoxelMultiAxisAM_bin.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/VoxelMultiAxisAM_bin.dir/src/main.cpp.o] Interrupt
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/VoxelMultiAxisAM_bin.dir/all' failed
make[1]: *** [CMakeFiles/VoxelMultiAxisAM_bin.dir/all] Interrupt
Makefile:94: recipe for target 'all' failed
make: *** [all] Interrupt
```
If you see/know anything that could be a reason for this problem I would greatly appreciate it if you would let me know! 

Thanks!
